apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-publisher
  namespace: default
  labels:
    app: rabbitmq-publisher
spec:
  selector:
    matchLabels:
      app: rabbitmq-publisher
  template:
    metadata:
      labels:
        app: rabbitmq-publisher
    spec:
      containers:
        - name: rabbitmq-publisher
          image: docker.io/pcsiszar/send:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: RABBIT_HOST
              value: rabbitmq.default.svc.cluster.local
            - name: RABBIT_USER
              value: user
            - name: RABBIT_PASSWORD
              value: PASSWORD
